services:
  web:
    env_file:
      - .env.demo
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    container_name: videoreview-web-demo
    ports:
      - "3000:3489"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: videoreview-db-demo
    environment:
      POSTGRES_USER: videoreview
      POSTGRES_PASSWORD: videoreview
      POSTGRES_DB: videoreview
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
