name: build-maintenance

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-maintenance:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: maintenance
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: maintenance/go.mod
      - name: Build maintenance CLI
        run: go build ./...
